### ISSUE TITLE
this should be global constants, not defines

### ISSUE THREAD

**Issue by Dyronix** [New-Creta/Rex#191] opened 2023-06-01 11:35 UTC
this should be global constants, not defines

_Originally posted by @RisingLiberty in https://github.com/New-Creta/Rex/pull/178#discussion_r1212357777_

**Comment by RisingLiberty** [comment] 2023-06-04 19:11
duplicate of https://github.com/New-Creta/Rex/issues/193

**Closed by RisingLiberty** 2023-06-04 19:11 UTC
